---
title: "GreenPAK^TM^ **勝手に**アプリケーションノート"
abstract: NeoPixelでランダムＬチカ
#/555をエミュレーションする
circle: KY技研
author: "@_K4ZUKI_"
comiket: 技術書典5
year: 2018
publisher: 印刷会社で印刷製本
docrevision: "1.0"
# front: images/front-image.png
verbcolored: true
# rmnote: false
strikeout: true
...
